tag-names:
  - name: datetime
    type: datetime
    value: '%Y%m%d%H%M'

builds:
  docker-make:
    context: /
    dockerfile: Dockerfile
    buildargs:
      - 'ENV_VAR=${ENV_VAR}'
    pushes:
      - 'on_branch:master=jizhilong/docker-make:latest'
    labels:
      - 'com.dockermake.git.describe={git_describe}'
    dockerignore:
      - .git
